### PR TITLE
Rename gentypeconfig.json to genTypeConfig.json

### PR DESCRIPTION
**Pull request by nhducit**
Fix #55

### CODE REVIEW

**Comment by ryyppy** [comment]
I want to drop in that if we want to rename that file, I would highly suggest looking for both versions of the filename to prevent breaking changes

**Comment by cristianoc** [comment]
It's been also suggested that the config options could be moved directly into bsconfig.json. (Still without removing support for genflowconfig.json, to avoid breaking changes). Avoids having to remember to move both files together in case of a repo reorg (it happened).

**Comment by nhducit** [comment]
@ryyppy thanks. I did not think about the breaking change.
@cristianoc it is a good idea

**Comment by ryyppy** [comment]
> It's been also suggested that the config options could be moved directly into bsconfig.json.

Yes! That would be really awesome, less files is usually better.. also having a sane default configuration would be awesome (maybe lang: untyped?)

**Comment by cristianoc** [comment]
All moved to bsconfing.json.

**Pull request closed without merging**
