### PR TITLE
Update 4_06_1 branch to master and add .opam file

### PR DESCRIPTION
**Pull request by wokalski**
This PR adds an .opam file and merges 4_06_1 with master. Unfortunately ppx_optcomp doesn't support OCaml 4.02.3 so this branch still isn't compatible with that version of OCaml.

### CODE REVIEW

**Comment by cristianoc** [comment]
@wokalski thanks for setting it up.
What's the command to build this with esy/opam?

**Comment by wokalski** [comment]
@cristianoc for opam, I think the standard workflow should work. I haven't used opam in some time now but you should be able to pin and build it like any other package. I tested it together with another project where i used it (I used `esy`'s `link` feature for that.)

**Comment by wokalski** [comment]
I found a way to build it with esy. It requires adding `esy.json` with:
```
{
  "source": "./genType.opam",
  "override": {}
}
```

Unfortunately, when I build it with `esy build` it won't build (even though it is built correctly when used as a `link`ed dependency)

```
info esy build 0.5.6 (using esy.json)
    ocamldep src/.GenType.eobjs/string_map.pp.ml.d (exit 2)
(cd _build/default && /Users/wczekalski/.esy/3______________________________________________________________/i/ocaml-4.7.1004-e5a2754f/bin/ocamldep.opt -modules -impl src/string_map.pp.ml) > _build/default/src/.GenType.eobjs/string_map.pp.ml.d
File "ext/map.cppo.ml", line 7, characters 2-4:
Error: Syntax error
error: command failed: 'dune' 'build' '-p' 'genType' '-j' '4' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1

esy: exiting due to errors above
```

**Comment by cristianoc** [comment]
@wokalski I get the same error.
Though `dune build` works fine.
Also, easy takes 1 minute "pause" each time I try to build again, not sure why.

Perhaps it's using a different ocaml version than 4_06_1, not sure.

**Comment by cristianoc** [comment]
Looks like it's using 4.7.

```
(cd _build/default && /Users/cristianoc/.esy/3______________________________________________________________/i/ocaml-4.7.1004-e5a2754f/bin/ocamlc.opt -w -30-40 -g -bin-annot -I src/.GenType.eobjs/byte -I /Users/cristianoc/.esy/3______________________________________________________________/i/ocaml-4.7.1004-e5a2754f/lib/ocaml/compiler-libs -no-alias-deps -o src/.GenType.eobjs/byte/TranslateTypeExprFromTypes.cmo -c -impl src/TranslateTypeExprFromTypes.re.ml)
```

**Comment by wokalski** [comment]
@cristianoc it seems like an esy bug. I'll report it. In any case, this PR is to the 4_06_1 branch. Can we merge it?

When it comes to proper upstreaming, I am considering writing a simple PPX which will allow conditional compilation just based on the OCaml version. In the current state of affairs, there's nothing that lets us efficiently compile conditionally. `ppx_optcomp` is 4.04.1+ (because of ppxlib). An alternative would be using `.ml` files and cppo for everything.

**Comment by cristianoc** [comment]
Aha I did not notice it was a PR to the branch.
I would not worry about conditional compilation. There's a difference also in the example, and generated, files. So it would end up being more complexity than it's worth.
I think we'll just switch to support 4.06 at some point, and stop new development on 4.02.3

**Comment by wokalski** [comment]
Great, I'm fine with this 👍. I'll add a comment in the 4.06.1 issue about the branch so that people can use it.

**Pull request merged**
