### PR TITLE
Migrate typescript example to create react app v2

### PR DESCRIPTION
**Pull request by nhducit**
currently typescript example is using a fork of create react app v1 with typescript support. Create react app v2 now support typescript by default.

Work around when doing this migration:
- Need to add `src/AutoAnnotate.bs.js` file to `exclude` in tsconfig.json file because this issue: https://github.com/Microsoft/TypeScript/issues/15230
 TLD; typescipt complain about empty file when `isolatedModules: true` (which is required in react-script v2)

Note: I have no idea why I cannot use `npm` to install dependencies when adding `react-scripts`, I need to use `yarn` instead that's why this PR introduce `yarn.lock` file

### CODE REVIEW

**Comment by nhducit** [comment]
this is the output of npm log when running `node ./scripts/run_integration_tests.js` look like the same issue happen on CI

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/duc/.fnm/node-versions/v10.15.0/installation/bin/node',
1 verbose cli   '/Users/duc/.fnm/current/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--no-save' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session 0943bb6a1fa207cd
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall typescript-react-example@0.1.0
7 info lifecycle typescript-react-example@0.1.0~preinstall: typescript-react-example@0.1.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 12516ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 34ms
14 silly install loadShrinkwrap
15 timing stage:rollbackFailedOptional Completed in 4ms
16 timing stage:runTopLevelLifecycles Completed in 12637ms
17 verbose stack TypeError: Cannot read property 'match' of undefined
17 verbose stack     at tarballToVersion (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
17 verbose stack     at inflatableChild (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
17 verbose stack     at BB.each (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
17 verbose stack     at tryCatcher (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Object.gotValue (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
17 verbose stack     at Object.gotAccum (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
17 verbose stack     at Object.tryCatcher (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
17 verbose stack     at Promise._settlePromiseFromHandler (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
17 verbose stack     at Promise._settlePromise (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
17 verbose stack     at Promise._settlePromiseCtx (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
17 verbose stack     at Async._drainQueue (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
17 verbose stack     at Async._drainQueues (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
17 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/duc/.fnm/node-versions/v10.15.0/installation/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
17 verbose stack     at runCallback (timers.js:705:18)
17 verbose stack     at tryOnImmediate (timers.js:676:5)
17 verbose stack     at processImmediate (timers.js:658:5)
18 verbose cwd /Users/duc/Documents/whiteMouse/genType/examples/typescript-react-example
19 verbose Darwin 18.2.0
20 verbose argv "/Users/duc/.fnm/node-versions/v10.15.0/installation/bin/node" "/Users/duc/.fnm/current/bin/npm" "install" "--no-save"
21 verbose node v10.15.0
22 verbose npm  v6.4.1
23 error Cannot read property 'match' of undefined
24 verbose exit [ 1, true ]
```

**Comment by cristianoc** [comment]
@nhducit I would love to modernize the TS example setup.
I don't know what to suggest to turn CI green, but maybe @ryyppy does.

**Comment by nhducit** [comment]
@cristianoc I fixed the CI issue after removing both package-lock.json file and `node_modules` folder then run `npm install` again. it seems the package-lock.json file is messed up when I install new dependencies.

@cristianoc @ryyppy should we switch to `yarn` for more stable lock file?

**Comment by cristianoc** [comment]
Thanks!

**Comment by cristianoc** [comment]
@nhducit I'll leave the answer to npm vs yarn to @ryyppy.

**Pull request merged**
