### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by wontheone1**
Some small improvements.

p.s.
Newbie question: I am learning about genType for the first time and saw usage of `.re.js` file extensions consistently. Is the extension used for generated js files for type annotations? I initially thought it might be a typo for `.bs.js.` files but I assume my initial assumption is wrong.

### CODE REVIEW

**Comment by wontheone1** [comment]
```
"gentypeconfig": {
    "language": "typescript" | "flow" | "untyped",
    "shims": {
      "ReasonReact": "ReactShim"
    }
  }
```

> shims
>
> e.g. Array<string> with format: "ReasonModule=JavaScriptModule"

^ Is this still true? From the example it looks like a JSON/JS object.

**Comment by wontheone1** [comment]
@ryyppy @cristianoc Hi could you check my PR and comment? Thank you!

**Comment by cristianoc** [comment]
@wontheone1 I have completely missed this PR!

**Comment by cristianoc** [comment]
Thanks a lot for doing it.

**Comment by wontheone1** [comment]
@cristianoc Thank you too!

**Pull request merged**
