### PR TITLE
Remove old .re.js extensions

### PR DESCRIPTION
**Pull request by ryyppy**
This should now be .gen.js

Thanks to @wontheone1 for pointing this out

### CODE REVIEW

**Comment by wontheone1** [comment]
@ryyppy Welcome, btw, I think there could be a short description of what the `*.gen.js` files do. I don't recall finding any official introduction to the functions of these files. (OFC, I am not the maintainer so this is just an opinion).

**Comment by ryyppy** [comment]
@wontheone1 It's described in this section [here](https://github.com/cristianoc/genType#testing-the-whole-setup):

> Save the file and rebuild the project with BuckleScript. You should now see a *.gen.tsx (for TypeScript, or *.gen.js for Flow) file with the same name (e.g. MyComponent.re -> MyComponent.gen.tsx).

Not sure if this is enough context, but so far ppl just usually went with the setup instructions and saw that they now have `.gen.X` files with all the content genType generates

**Comment by wontheone1** [comment]
👍 @ryyppy I see thanks for the pointer.

**Comment by cristianoc** [comment]
Thank you!

**Pull request merged**
