### PR TITLE
Dependent projects: turn on by default, and document the feature.

### PR DESCRIPTION
**Pull request by cristianoc**
Turn on support for dependent projects by default.
Document the feature.

### CODE REVIEW

**Comment by cristianoc** [comment]
@coobaha
@sync

**Comment by Coobaha** [comment]
@cristianoc 👍 I will try it soon!

**Comment by sync** [comment]
Ci build passed on my side thank you

**Comment by Coobaha** [comment]
Works like a charm, thanks! ❤️

**Pull request merged**
